###########################
#Project=AKS Landing Zone #
#Ownwr: Subinoy.          #
###########################
#braching
#trigger
#parameete
#variable
#pr

# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - feature/review1.0.0
    exclude:
      - main

parameters:
  - name: environment
    displayName: 'Target Environment' 
    type: string
    default: 'prod'
    values:
      - dev
      - stage
      - prod 

stages:
  - stage: PreCommit
    jobs:
      
    - job: 
      pool: dccloud
      steps:
      - task: TerraformInstaller@0

    

    
      


